module.exports = {
    AUTH_FAILED: "AUTH_FAILED",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    INVALID_FILE: "INVALID_FILE",
    INVALID_FILE_HEADER_NAME: "INVALID_FILE_HEADER_NAME",
    INVALID_FILE_DATA: "INVALID_FILE_DATA",
    BAD_JSON: "BAD_JSON",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    INVALID_DATA: "INVALID_DATA"
};
